spring.application.name=ParkingAdvanced

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.api.key=${APP_API_KEY}


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


weather.api.url=https://api.open-meteo.com/v1/forecast?latitude=41.045&longitude=28.940&hourly=rain&timezone=auto

weather.rain-threshold=0.3

python.api.predict.url=http://python-service:5000/api/v1/parking
python.api.retrain.url=http://python-service:5000/api/v1/model/retrain




parking.lots[0].id=1
parking.lots[0].name=H0
parking.lots[0].capacity=200
parking.lots[1].id=2
parking.lots[1].name=H1
parking.lots[1].capacity=250
parking.lots[2].id=3
parking.lots[2].name=H2
parking.lots[2].capacity=180
parking.lots[3].id=4
parking.lots[3].name=H3
parking.lots[3].capacity=150
