spring.application.name=ParkingDemoV2

spring.datasource.url=jdbc:postgresql://localhost:5432/parking_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_DATABASE_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

python.api.url=http://127.0.0.1:5001
weather.api.url=https://api.open-meteo.com/v1/forecast?latitude=41.0082&longitude=28.9784&hourly=rain&forecast_days=1

parking.total-capacity=100

spring.docker.compose.enabled=false